[workspace]
members = [
]
[package]
name = "list"
authors = ["C2Rust"]
version = "0.0.0"
publish = false
edition = "2021"
autobins = false

[lib]
name = "list"
path = "lib.rs"
crate-type = ["staticlib", "rlib"]
[[bin]]
path = "src/test_list.rs"
name = "test_list"
[dependencies]
libc= "0.2"
